### ISSUE TITLE
add prisma-studio in docker-compose.yml

### ISSUE THREAD

**Issue by Luchanso** [fastup-kit/node-backend#29]
https://hub.docker.com/r/timothyjmiller/prisma-studio
```yml
version: '3.7'
services:
  prisma-studio:
    container_name: prisma-studio
    image: timothyjmiller/prisma-studio:latest
    restart: unless-stopped
    env_file:
     - .env
    ports:
      - ${PRISMA_STUDIO_PORT}:5555
```
